mae_hdf5_prefix: "mae"
readable_names:
 "Lipidomics, positive | transformed": "Lipidomics Set 1 (P)"
 "Lipidomics, negative | transformed": "Lipidomics Set 1 (N)"
 "Lipidomics-SPLINE | positive":  "Lipidomics Set 2"
 "Very long chain fatty acids | batch-adjusted": "VLCFA"
 "Very long chain fatty acids": "VLCFA"
 "Acylcarnitines | batch-adjusted | imputed missing values": "Acylcarnitines"
 "Amino acids | batch-adjusted | imputed missing values": "Amino acids"
 "Proteomics | imputed missing values": "Proteomics"
 "Proteomics | with missing values": "Proteomics"
 "Proteomics-IPP": "Proteomics-IPP"
 "mRNA-seq-2 | batch-adjusted | corrected": "mRNA-seq"
 "miRNA-seq, mature | batch-adjusted | cell-type adjusted": "miRNA-seq"
 "miRNA-seq, mature | batch-adjusted": "miRNA-seq"
 "miRNA qRT-PCR": "miRNA qRT-PCR"
 "EM-seq | cell-type adjusted | 100,000 most variable CpG sites": "EM-seq (var)"
 "EM-seq | cell-type adjusted | 100,000 random CpG sites": "EM-seq (random)"
 "Metabolomics": "Metabolomics"

experiment_names:
  PCA:
  - "Lipidomics, positive | transformed"
  - "Lipidomics, negative | transformed"
  - "Lipidomics-SPLINE | positive"
  - "Very long chain fatty acids | batch-adjusted"
  - "Acylcarnitines | batch-adjusted | imputed missing values"
  - "Amino acids | batch-adjusted | imputed missing values"
  - "Proteomics | imputed missing values"
  - "Proteomics-IPP"
  - "mRNA-seq-2 | batch-adjusted | corrected"
  - "miRNA-seq, mature | batch-adjusted | cell-type adjusted"
  - "miRNA qRT-PCR"
  - "EM-seq | cell-type adjusted | 100,000 most variable CpG sites"
  RLM:
  - "Lipidomics, positive | transformed"
  - "Lipidomics, negative | transformed"
#  - "Lipidomics-SPLINE | positive"
  - "Very long chain fatty acids | batch-adjusted"
#  - "Very long chain fatty acids | unscaled"
  - "Acylcarnitines | batch-adjusted | imputed missing values"
  - "Amino acids | batch-adjusted | imputed missing values"
#  - "Proteomics-IPP"
#  - "Proteomics | imputed missing values"
#  - "mRNA-seq-2 | batch-adjusted | corrected"
#  - "miRNA-seq, mature | batch-adjusted | cell-type adjusted"
#  - "miRNA qRT-PCR"
#  - "EM-seq | cell-type adjusted | 100,000 most variable CpG sites"
  MOFA:
  - "Lipidomics, positive | transformed"
  - "Very long chain fatty acids | batch-adjusted"
  - "Acylcarnitines | batch-adjusted | imputed missing values"
  - "Amino acids | batch-adjusted | imputed missing values"
  - "Proteomics | imputed missing values"
  - "Proteomics-IPP"
  - "mRNA-seq-2 | batch-adjusted | corrected"  
  - "miRNA-seq, mature | batch-adjusted | cell-type adjusted"
  - "miRNA qRT-PCR"
  - "EM-seq | cell-type adjusted | 100,000 most variable CpG sites"
  CV:
  - "Lipidomics, positive | transformed"
  - "Lipidomics, negative | transformed"
  - "Lipidomics-SPLINE | positive"
  - "Very long chain fatty acids"
  - "Acylcarnitines"
  - "Amino acids"	
  - "Proteomics | with missing values"
  - "Proteomics-IPP"
  - "mRNA-seq-2 | batch-adjusted | corrected"
  - "miRNA-seq, mature | batch-adjusted | cell-type adjusted"
  - "miRNA qRT-PCR"
  - "EM-seq | cell-type adjusted | 100,000 most variable CpG sites"
  - "EM-seq | cell-type adjusted | 100,000 random CpG sites"
  DIABLO:
  - "Lipidomics, positive | transformed"
#  - "Lipidomics, negative | transformed"
  - "Lipidomics-SPLINE | positive"
  - "Very long chain fatty acids | batch-adjusted"
  - "Acylcarnitines | batch-adjusted | imputed missing values"
  - "Amino acids | batch-adjusted | imputed missing values"
  - "Proteomics | imputed missing values"
  - "Proteomics-IPP"
  - "mRNA-seq-2 | batch-adjusted | corrected"  
  - "miRNA-seq, mature | batch-adjusted | cell-type adjusted"
  - "miRNA qRT-PCR"
  - "EM-seq | cell-type adjusted | 100,000 most variable CpG sites"
#  - "EM-seq | cell-type adjusted | 100,000 random CpG sites"
output_directory:
  PCA: "Output/PCA"
  RLM: "Output/RLM"
  MOFA: "Output/MOFA"
  DIABLO: "Output/DIABLO"
  PEA: "Output/PEA"
  CV: "Output/CV"
sample_selection:
  include_MALE: TRUE
  include_FEMALE: TRUE
additional_data_types:
  include_hematology: FALSE
  include_phenotype: FALSE
num_MOFA_factors: 12
PEA_input:
  DIABLO:
    "Lipidomics, positive": "DIABLO/XYloadings_Lipidomics__positive.csv"
    "Lipidomics, negative": "DIABLO/XYloadings_Lipidomics__negative.csv"
    "Very long chain fatty acids | batch-adjusted": "DIABLO/XYloadings_Very_long_chain_fatty_acids___batch-adjusted.csv"
    "Acylcarnitines | batch-adjusted | imputed missing values": "DIABLO/XYloadings_Acylcarnitines___batch-adjusted___imputed_missing_values.csv"
    "Amino acids | batch-adjusted | imputed missing values": "DIABLO/XYloadings_Amino_acids___batch-adjusted___imputed_missing_values.csv"
    "Proteomics | imputed missing values": "DIABLO/XYloadings_Proteomics___imputed_missing_values.csv"
  MOFA:
    #"Lipidomics, positive": "MOFA/factorweights_Lipidomics__positive___transformed.csv"
    "Very long chain fatty acids | batch-adjusted": "MOFA/factorweights_Very_long_chain_fatty_acids___batch-adjusted.csv"
    "Acylcarnitines | batch-adjusted | imputed missing values": "MOFA/factorweights_Acylcarnitines___batch-adjusted___imputed_missing_values.csv"
    "Amino acids | batch-adjusted | imputed missing values": "MOFA/factorweights_Amino_acids___batch-adjusted___imputed_missing_values.csv"
    "Proteomics | imputed missing values": "MOFA/factorweights_Proteomics___imputed_missing_values.csv"
    "Proteomics-IPP": "MOFA/factorweights_Proteomics-IPP.csv"
    "mRNA-seq-2 | batch-adjusted | corrected": "MOFA/factorweights_mRNA-seq-2___batch-adjusted___vst___corrected.csv"
    #"EM-seq | cell-type adjusted | 100,000 most variable CpG sites": "MOFA/factorweights_EM-seq___cell-type_adjusted___100_000_most_variable_CpG_sites.csv"
PEA_databases: "all"
PEA_rankings:
  DIABLO:
  - "comp1"
  - "comp2"
  MOFA:
  - "Factor1"
  - "Factor2"
  - "Factor3"
  - "Factor4"
  - "Factor5"
  - "Factor6"
  - "Factor7"
  - "Factor8"
  - "Factor9"
  - "Factor10"
  - "Factor11"
  - "Factor12"

